config/routes.rb
Rails.application.routes.draw do
  get 'say/hello'

  get 'say/goodbye'

  root "static_pages#home"

  #get 'static_pages/home'

  get 'static_pages/help'

  get 'static_pages/about'

  resources :articles
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
    
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :content)
    end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
  end

  def goodbye
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(title = 'Untitled')
    base_title = " | Sanad's Blog"
    if title.empty?
      title = 'Untitled'
    end
    return title + base_title
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label' %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<%= provide :title, "Edit Article" %>
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<%= provide(:title, "All Articles") %>
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table class="table table-stripped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.content %></td>
        <td><%= link_to 'Show', article, class: 'btn btn-primary' %></td>
        <td><%= link_to 'Edit', edit_article_path(article), class: 'btn btn-warning' %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' },
        class: 'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path, :class => 'btn btn-default' %>

app/views/articles/new.html.erb
<%= provide :title, "Add Article" %>
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= provide :title, "Article Details" %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<%= link_to  'Edit', edit_article_path(@article), :class => 'btn btn-default' %> |
<%= link_to 'Back', articles_path, class: 'btn btn-default' %>

app/views/layouts/_footer.html.erb
<footer>
  <small>The Blog is produced to you by Sanad Bukiran</small>
  <small>Copyright (c) 2016 to Sanad Bukiran All Rights Reserved.</small>
  <nav>
    <ul>
      <li><%= link_to "About", static_pages_about_path %></li>
      <li><%= link_to "Contact", "#" %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Sanad's Blog", root_path, id: "logo", class: "navbar-brand" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", static_pages_help_path %></li>
        <li><%= link_to "About", static_pages_about_path %></li>
        <li><%= link_to "Articles", articles_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>

  <body>
    <div class="container">
    <%= render "layouts/header" %>


      <%= yield %>

    <%= render "layouts/footer" %>
    </div>
  </body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<%= provide(:title, 'hello page') %>
<h1>Hello from Rails 5!</h1>
<h3>It is now <%= @time %></h3>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>About Application</h1>
<p>
  this is the about page, generated by me!
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>

<div class="center jumbotron">
  <h1>Welcome to Sanad's Blog</h1>

<h2>
  This is the home page for <%= link_to "Sanad's Blog", controller: 'static_pages',
  action: 'home'  %> Demo Application.
</h2>
<%= link_to "Sign Up Now!", "#", class: 'btn btn-lg btn-primary' %>
</div>
<%= link_to image_tag("rails.png", alt: "Rails Logo"), controller: 'static_pages',
action: 'home' %>